name: PR deploy

on:
  pull_request:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Check lint
        run: yarn lint

      - name: Build
        run: yarn build
    