name: PR deploy

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  coverage:
    name: Test Coverage Test
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3

      - name: Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2

  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm i -g yarn

      - name: Check lint
        run: yarn lint

      - name: Build
        run: yarn build

  deploy:
    name: Deploy to Vercel
    needs: [coverage, build]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : Deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}



