name: Storybook deploy

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkbox
      - uses: actions/checkout@v1
        run: yarn

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name : Storybook build
        run: yarn build-storybook

      - name: Deploy storybook to Chromatic
        run: yarn chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
